### PR TITLE
Fixes ssh-agent forwarding in current window.

### PR DESCRIPTION
**Pull request by itsamenathan**
This will set the correct SSH_AUTH_SOCK for the current window. Meaning that ssh-agent forwarding will just work on any window.

### CODE REVIEW

**Comment by itsamenathan** [comment]
Anyone test this?

**Comment by dan9186** [comment]
What's the means to test this? I forward my ssh agent all the time and have not been aware of an issue.

**Comment by itsamenathan** [comment]
# Summery 
This will set SSH_AUTH_SOCK if it is not set.  This way, ssh-agent forwarding will work on old stale tmux windows after you start using them. 

## Example
1. Login to server where tmux is already running `ssh -A example.com`
2. `git clone git@github.com:myzsh/myzsh.git`
3. This should fail the first time, because  SSH_AUTH_SOCK isn't set.
4. Run git command again, and it will work.

## Potential Problems
 SSH_AUTH_SOCK will get set to nothing, if `tmux show-environment` doesn't contain SSH_AUTH_SOCK

**Comment by brimstone** [comment]
This seems to work. Going to rebase then merge.

**Comment by brimstone** [comment]
@itsamenathan it looks like the rebase confused github. This branch is merged in though.

**Pull request closed without merging**
